### ISSUE TITLE
Write blog post on most popular destinations for tourists are in nepal

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/to-do-list#10]
data: https://github.com/Code4Nepal/data/blob/master/datasets/Tourist%202018/Places%20Visited%20.csv

example of a blog post: http://codefornepal.org/2018/09/tourism-nepal-visitnepal2020/

@pratimakandel - would you be interested to write this in 5-10 days?

**Comment by pratimakandel** [comment]
Dear Ravi,

I will work on it.

Thank you.
Pratima Kandel,
