### ISSUE TITLE
 Edit blog on Forest of Nepal 

### ISSUE THREAD

**Issue by roshghimire** [Code4Nepal/to-do-list#3]
Namrata has penned a blog on forest of Nepal. I have added few comments. Please review.
Link: https://docs.google.com/document/d/11MghvpkxmnuNoN-QjVu9RYzfLbHJGfCxyRKqykD06M0/edit?ts=5b44303a

**Comment by ravinepal** [comment]
thanks. will do in a few days.

**Comment by ravinepal** [comment]
this has been published: http://codefornepal.org/en/2018/07/2170/
