### ISSUE TITLE
Write blog post on which province has the highest population and household

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/to-do-list#4]
Here's the data from the CBS: https://github.com/ravinepal/data/blob/d3075b1a6758024d9096bbab9fa4b85a70d49b1f/provincial%20data/tabula-Population_Province_Level_CBS_2018.csv

@pratimakandel - are you interested? You could even use Carto to create an interactive map. 

Here's example of provincial map: https://codefornepal.carto.com/viz/857767fe-347c-49a6-98d2-78e081b2d152/public_map

**Comment by pratimakandel** [comment]
Dear Ravi ,

Thank you !! I am working on it I will let you know if anything comes up !!

Sincerely yours,
Pratima Kandel.

**Comment by pratimakandel** [comment]
Dear Ravi,

Here is the link to the map
https://pratimakandel.carto.com/builder/52b0c4a2-357c-44df-afe3-6825bc411b3e/embed.
Please let me know if I need to edit anything.

Thank you.


Sincerely yours,
Pratima Kandel.

**Comment by ravinepal** [comment]
thanks, @pratimakandel. good start. May I ask you think from a general reader's perspective - would a high school student in Jhapa understand which province has the highest population based on the map you created? Also, do you think we should write a few sentences which we can publish as a blog post? 

For inspiration, check this out: http://codefornepal.org/2018/01/province-poverty-nepal/ 

There is no rush - if you won't mind updating your map and then writing by tuesday/wednesday - that will be great. pls lmk if you have qs.

**Comment by pratimakandel** [comment]
Dear Ravi,

I am working on it.

Sincerely yours,
Pratima Kandel.

**Comment by pratimakandel** [comment]
Dear Ravi,

I have updated the map and wrote a few sentences about it.
https://pratimakandel.carto.com/builder/52b0c4a2-357c-44df-afe3-6825bc411b3e/embed

However, the given data states that the total population is around 26m but
all over the internet in other sites, it is estimated around 29m.

Here is the attached document. Please let me know if I need to make any
changes.


Thank you.



Sincerely yours,
Pratima Kandel.

**Comment by ravinepal** [comment]
Thank you, @pratimakandel. Much appreciated. I think the document did not get attached - would you mind emailing that to me perhaps when you have time? 

It's good to know that total data based on this CBS document is less than what other internet sites are saying? According to 2011 census the total population was 26,494,504. https://nepalmap.org/profiles/country-NP-nepal/

**Comment by pratimakandel** [comment]
Dear Ravi,

Here is the attached document. Let me know if  I have to make any changes.


Sincerely yours,
Pratima Kandel.

**Comment by ravinepal** [comment]
hi pratima - thank you so much and sorry for the delay. i created a chart and published the post. http://codefornepal.org/en/2018/08/province_nepal_population/ 

I've given you credit at the end of the post. We can talk more next weekend other projects.
